name: hello world
on: 
  push:
    branches: [ master ]
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TODAY=$(date +%y-%m-%d)"  >> $GITHUB_ENV
      - run: echo "Hello World", today is $TODAY